### ISSUE TITLE
Design issue?

### ISSUE THREAD

**Issue by jhumphreys007** [zcutlip/nvram-faker#2]
I ran this against a project (a router) where the firmware had been unbundled and the file system recovered.

First, under the /lib directory in the target firmware, there are 3 NVRAM-related libraries
- libnvram.so
- libnvram.so.0
- libnvram-0.9.28.so

The first two are symbolic links to the third file, so I think the last file is the library that needs to be replaced with the intercepting library.

Second, the design of this solution does not appear to take into account that the NVRAM may be partitioned.   If you run the 'strings' function on the other files in the file system, you can find the calls to the NVRAM functions.   In the case I was investigating, I found strings like

platform=`nvram_get 2860 Platform`
iNIC_Mii_en=`nvram_get rtdev InicMiiEnable`

The formatting during this writing ate the back-quotes and left the rest of the line in the shaded block.   So, if you can imaging these with back-quotes around the portion following the "=" sign, these look like shell script commands.   But there is also a second argument (actually the 1st in the command) that seems to indicate that the NVRAM might be partitioned.   What I do know is that, when I looked at the NVRAM parameters in the nvram.ini file vs what I get from my 'strings' search,

- None of the parameters in the nvram.ini file matched up against the second parameter being retrieved via these shell script calls from the 'strings' search.
- I found a total of 159 unique NVRAM parameters across two partitions in the 'strings' search and yet only 41 symbols appeared in the nvram.ini file.

**Comment by zcutlip** [comment]
Hi, I'm sorry it's taken so long to reply to this issue.

I'm not sure if I completely understand the problem you're describing, but there are a few things I can say about nvram-faker that may clarify how it should be used.

The nvram-faker library should be LD_PRELOADed and in doing so, it intercepts library calls to nvram_get(). For most embedded nvram libraries that I have seen, the nvram_get() function takes a single argument that is a char * and returns a char *. As such, this is the function signature of nvram-faker's nvram_get() function. I'm not sure if you're saying your system's nvram library has a different API, but if so, nvram-faker probably won't work with it.

Regarding the .ini file, the one included really is an example only. You should create your own that contains nvram config parameters that your target is expects to find. When you use nvram-faker, if your .ini file is missing parameters, you will see colorized output printed to the console for each missing parameter. You can then edit your config as needed and rerun your program. If you have shell access to a live system, you should be able to extract all of the nvram configuration from the proper mtd partition. Using that configuration, you should be able to generate a matching .ini file without guesswork.

I hope this helps.

Please reopen the issue if it does not.
